version: "3"

x-uffizzi:
  ingress:
    service: nginx
    port: 8081

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx
  
  online-go:
    image: "${ONLINE_GO_IMAGE}"
    entrypoint: /bin/sh
    command: 
      - "-c"
      - "export UFFIZZI_URL=$$UFFIZZI_URL && export SERVER_URL=$$UFFIZZI_URL/server && npm run dev"
    deploy:
          resources:
            limits:
              memory: 4000M
  