version: "3"

x-uffizzi:
  ingress:
    service: online-go
    port: 8080

services:

  online-go:
    image: "${ONLINE_GO_IMAGE}"
    entrypoint: /bin/sh
    command: 
      - "-c"
      - "OGS_BACKEND=UFFIZZI UFFIZZI_URL=$$UFFIZZI_URL/ npm run dev"
    ports:
      - "8080:8080"
    deploy:
          resources:
            limits:
              memory: 4000M
  