version: "3"

x-uffizzi:
  ingress:
    service: online-go
    port: 8082

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx
  
  online-go:
    image: "${ONLINE_GO_IMAGE}"
    entrypoint: /bin/sh
    command: 
      - "-c"
      - "UFFIZZI_URL=$$UFFIZZI_URL npm run dev:uffizzi"
    ports:
      - "8081:8081"
    deploy:
          resources:
            limits:
              memory: 4000M
  