version: "3"

x-uffizzi:
  ingress:
    service: online-go
    port: 8080

services:

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx:/etc/nginx
  
  online-go:
    image: "${ONLINE_GO_IMAGE}"
    entrypoint: /bin/sh
    command: 
      - "-c"
      - "OGS_BACKEND=PRODUCTION && UFFIZZI_URL=$$UFFIZZI_URL/ yarn dev"
    deploy:
          resources:
            limits:
              memory: 4000M
  